#!/bin/bash

# Move to /home/$USER/.local/bin

# Initialize variables
ret_out=false
# Parse options
while getopts ":o" opt; do
  case ${opt} in
    o )
      ret_out=true
      ;;
    \? )
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

DOM="${1:-$SALT_DOUBLE}"
full=$(saltthepass -h $SALT_HASHER -p $SALT_MASTER -d $DOM)
part=${full:0:$SALT_LENGTH}
if [ $DOM == $SALT_DOUBLE ]; then
  part=${part}${part}
fi

if [ $ret_out == true ]; then
  echo $part
else
  echo $part | xclip -selection c -rmlastnl
fi
