code --install-extension AffenWiesel.matlab-formatter
code --install-extension bierner.markdown-mermaid
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension estivo.csv-editor
code --install-extension fabiospampinato.vscode-diff
code --install-extension file-icons.file-icons
code --install-extension fosshaas.fontsize-shortcuts
code --install-extension gerane.Theme-DarkRoomContrast
code --install-extension Gimly81.matlab
code --install-extension GitHub.github-vscode-theme
code --install-extension hediet.vscode-drawio
code --install-extension janisdd.vscode-edit-csv
code --install-extension jkjustjoshing.vscode-text-pastry
code --install-extension KevinRose.vsc-python-indent
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.sublime-keybindings
code --install-extension njpwerner.autodocstring
code --install-extension rebornix.toggle
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension swindh.enumerator
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension waderyan.gitblame
code --install-extension yzhang.markdown-all-in-one
